# Generated by Django 4.0.6 on 2022-08-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjangodockerUser',
        ),
    ]
